config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'users/new'
  get 'users/edit'
  get "search/index"
  get 'submissions/search'

  get 'welcome/index'
  root 'welcome#index' # make welcome#index the default root page

  resources :authors, :collections, :languages, :media, :translators, :works
  resources :submissions

  # Add users as a RESTful resource.
  resources :users

  # Add user_sessions as a RESTful resource and set up a couple of
  # URL-friendly routes for 'login' and 'logout'
  resources :user_sessions
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  # Set up CanCan automatic authorization on all methods. See models/ability.rb.
  load_and_authorize_resource
  
    #----------------------------------------------------------------------------
    def index
      @collections = Collection.all
    end

    #----------------------------------------------------------------------------
    def show
      @collection = Collection.find(params[:id])
    end

    #----------------------------------------------------------------------------
    def new
      # We build a blank collection here so that @collection in the view won't be nil.
      @collection = Collection.new
    end

    #----------------------------------------------------------------------------
    def edit
      @collection = Collection.find(params[:id])
    end

    #----------------------------------------------------------------------------
    def create
      # Build a new Collection object from the given parameters.
      @collection = Collection.new(collection_params)
      # Try to save it to the DB. If successful, redirect to show, otherwise
      # re-render the new page.
      if @collection.save
        redirect_to @collection
      else
        # Use "render" so we will reuse the same @collection field, thus repopulating
        # the form.
        render 'new'
      end

      # Dump the parameters
      # render plain: params[:collection].inspect
    end

    #----------------------------------------------------------------------------
    def update
      @collection = Collection.find(params[:id])

      if @collection.update(collection_params)
        redirect_to @collection
      else
        render 'edit'
      end
    end

    #----------------------------------------------------------------------------
    def destroy
      @collection = Collection.find(params[:id])
      @collection.destroy

      redirect_to collections_path
    end

    #----------------------------------------------------------------------------
    private
      def collection_params
        params.require(:collection).permit(:name)
      end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<p><%= link_to 'Back', collections_path %></p>

<% disabled ||= false # Form is enabled by default %>

<%= form_for @collection do |f| %>

  <%= render 'error', obj: @collection %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', readonly: disabled  %>
  </div>

  <%= f.submit style: disabled ? "display:none" : "" %>

<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

app/views/collections/index.html.erb
<h1>Collections</h1>

<% if can? :create, @collection %>
<p><%= link_to 'New Collection', new_collection_path %></p>
<% end %>

<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @collections.each do |collection| %>
    <tr>
      <td><%= collection.name %></td>
      <td><%= link_to 'Show', collection_path(collection) %></td>
      <% if can? :update, Collection %>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection_path(collection),
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>

</table>

app/views/collections/new.html.erb
<h1>Create New Collection</h1>

<%= render 'form' %>

app/views/collections/show.html.erb
<h1>Collection Detail</h1>

<%= render 'form', :disabled => true %>