config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'users/new'
  get 'users/edit'
  get "search/index"
  get 'submissions/search'

  get 'welcome/index'
  root 'welcome#index' # make welcome#index the default root page

  resources :authors, :collections, :languages, :media, :translators, :works
  resources :submissions

  # Add users as a RESTful resource.
  resources :users

  # Add user_sessions as a RESTful resource and set up a couple of
  # URL-friendly routes for 'login' and 'logout'
  resources :user_sessions
  get 'login', to: 'user_sessions#new'
  get 'logout', to: 'user_sessions#destroy'

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :work
  belongs_to :author
  belongs_to :translator
  belongs_to :language
  belongs_to :medium

  validates :medium_id, presence: true
  validates :language_id, presence: true
  validates :translator_id, presence: true
  validates :author_id, presence: true
  validates :work_id, presence: true
  validates :title, presence: true, length: { minimum: 5 }

  def self.search(title=nil, translator=nil, author=nil, work=nil, start_date=nil, end_date=nil)
    results = all
    results = results.where("submissions.title LIKE ?", "%#{title}%") unless title.blank?
    results = results.where("submissions.publication_year >= ?", "#{start_date}") unless start_date.blank?
    results = results.where("submissions.publication_year <= ? ", "#{end_date}" ) unless  end_date.blank?
    results = results.joins(:translator).where("translators.name LIKE ?", "%#{translator}%") unless translator.blank?
    results = results.joins(:author).where("authors.name LIKE ?", "%#{author}%") unless author.blank?
    results = results.joins(:work).where("works.title LIKE ?", "%#{work}%") unless work.blank?
    return results

  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  load_and_authorize_resource

  # Export these to the application helper.
  helper_method :sort_column, :sort_direction

  #----------------------------------------------------------------------------
  def index
    # Join with translator for sorting by translator name.
    @submissions = Submission.joins(:translator)

    # Possibly limit to those submissions that are approved or not.
    if cannot? :update, Submission
      # Anonymous users only see approved things.
      @submissions = @submissions.where('approved = 1')
    else
      # Otherwise, URL allows a choice.
      if params[:approved] == '1'
        @submissions = @submissions.where('approved = 1')
      elsif params[:approved] == '0'
        @submissions = @submissions.where('approved = 0')
      end
    end

    # Possibly limit to those submissions that need approval.
    if params[:completed] == '1'
      @submissions = @submissions.where('completed = 1')
    elsif params[:completed] == '0'
      @submissions = @submissions.where('completed = 0')
    end

    # Possibly limit to those assigned to the current user.
    if params[:assigned]
      @submissions = @submissions.where('entry_id = %d' % current_user.id)
    end

    # Search, order, and paginate.
    @submissions = @submissions.
      search( params[:title], params[:translator],
        params[:author], params[:work],
        params[:start_date], params[:end_date]
      ).
      order(sort_column + " " + sort_direction).
      paginate(:per_page => 20, :page => params[:page])

    # Display error if we have no submissions.
    if @submissions.blank?
      flash[:error] = "There are no submissions matching that criteria."
    end
  end

  #----------------------------------------------------------------------------
  def show
    @submission = Submission.find(params[:id])
  end

  #----------------------------------------------------------------------------
  def new
    # We build a blank submission here so that @submission in the view won't be nil.
    @submission = Submission.new
  end

  #----------------------------------------------------------------------------
  def edit
    @submission = Submission.find(params[:id])
  end

  #----------------------------------------------------------------------------
  def create
    # Build a new Submission object from the given parameters.
    @submission = Submission.new(submission_params)

    # New submissions default to unapproved.
    @submission.approved = 0
    @submission.completed = 0

    # Try to save it to the DB. If successful, redirect to show, otherwise
    # re-render the new page.
    if @submission.save
      redirect_to @submission
    else
      # Use "render" so we will reuse the same @submission field, thus repopulating
      # the form.
      render 'new'
      #render plain: params[:submission].inspect
    end

  end

  #----------------------------------------------------------------------------
  def update
    @submission = Submission.find(params[:id])

    # If the updated entry is being approved, capture the current user doing
    # the approving.
    if params[:submission][:approved] == "1"
      @submission.editor_id = current_user.id
    end

    if @submission.update(submission_params)
      redirect_to @submission
    else
      render 'edit'
    end
  end

  #----------------------------------------------------------------------------
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to submissions_path
  end

  #----------------------------------------------------------------------------
  private
    def submission_params
      params.require(:submission).permit(
        :title, :work_id, :author_id,
        :language_id, :medium_id,
        :translator_id, :isbn, :oclc, :edition,
        :is_prose, :is_poetry, :medium_id,
        :publication_year, :notes, :approved, :entry_id, :completed)
    end

    def sort_column
      # See if the sort column is one of the known column names, otherwise
      # default to title.
      %w[title publication_year translators.name completed].include?(params[:sort]) ? params[:sort] : "title"
    end

    def sort_direction
      # See if the current direction param is in the array (either asc or
      # desc), if not, default to "asc".
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_adv_search_form.html.erb
<%# Advanced search form %>
<div id="adv_search" class="collapse" style="margin-top: 10px; padding: 10px; background-color: lightgrey">

  <%# To make some of these dropdowns use the following syntax, although I'm
    not sure dropdowns are the best option. Having text boxes and using
    the LIKE query provides some great flexibility.

    collection_select(:submission, :translator_id, Translator.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select'})
  %>

  <%= form_tag(submissions_path, :method => "get", id: "adv-search-form", class: 'form') do %>

    <%# Add hidden sort and direction to persist these on a search. %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>

    <div class="form-group">
      <%= label_tag "Title", nil, class:'mr-2' %>
      <%= text_field_tag :title, params[:title], class:'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag "Translator", nil, class:'mr-2' %>
      <%= text_field_tag :translator, params[:translator], class:'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag "Author", nil, class:'mr-2' %>
      <%= text_field_tag :author, params[:author], class:'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag "Work", nil, class:'mr-2' %>
      <%= text_field_tag :work, params[:work], class:'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag "Start Year", nil, class:'mr-2' %>
      <%= text_field_tag :start_date, params[:start_date], class:'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag "End Year", nil, class:'mr-2' %>
      <%= text_field_tag :end_date, params[:end_date], class:'form-control' %>
    </div>

    <%= submit_tag "Search", :name => nil, class:'btn btn-primary ml-2 mr-2' %>

  <% end # advanced search form %>

</div>

app/views/submissions/_form.html.erb
<% disabled ||= false # Form is enabled by default %>

<%= form_for @submission do |f| %>

  <%= render 'error', obj: @submission %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= f.label :work %>
    <%= f.collection_select(:work_id, Work.all, :id, :title, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.collection_select(:author_id, Author.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= f.label :language %>
    <%= f.collection_select(:language_id, Language.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= f.label :translator %>
    <%= f.collection_select(:translator_id, Translator.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= f.label :isbn %>
    <%= f.text_field :isbn, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= f.label :oclc %>
    <%= f.text_field :oclc, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= f.label :edition %>
    <%= f.text_field :edition, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-check">
    <%= f.label :is_prose, class:'form-check-label' do %>
      <%= f.check_box :is_prose, class: 'form-check-input', disabled: disabled %>
      Is Prose?
    <% end %>
  </div>
  <div class="form-check">
    <%= f.label :is_poetry, class:'form-check-label' do %>
      <%= f.check_box :is_poetry, class: 'form-check-input', disabled: disabled %>
      Is Poetry?
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :medium %>
    <%= f.collection_select(:medium_id, Medium.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= f.label :publication_year %>
    <%= f.text_field :publication_year, class: 'form-control', readonly: disabled %></div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: 'form-control', readonly: disabled %>
  </div>

  <% if can? :update, @submission %>
    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-check">
        <%= f.label :completed, class:'form-check-label' do %>
          <%= f.check_box :completed, class: 'form-check-input', disabled: disabled %>
          Completed?
        <% end %>
      </div>
    </div>
  <% end %>

  <% if can? :approve, @submission %>
    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-check">
        <%= f.label :approved, class:'form-check-label' do %>
          <%= f.check_box :approved, class: 'form-check-input', disabled: disabled %>
          Approved?
        <% end %>
      </div>
    </div>

    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-group">
        <%= f.label "Assign To" %>
        <%= f.collection_select(:entry_id, User.where(role: 'entry'), :id, :email, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
      </div>
    </div>
  <% end %>

  <%= f.submit style: disabled ? "display:none" : "" %>

<% end %>

app/views/submissions/_pagination.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @submissions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/submissions/_submissions.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @submissions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

app/views/submissions/index.html.erb
<% if @approved == 0 %>
  <h1>Unapproved Submissions</h1>
<% else %>
  <h1>Submissions</h1>
<% end %>

<% if can? :create, Submission %>
  <p><%= link_to 'New Submission', new_submission_path %></p>
<% end %>

<%# --- Display search forms --------------------------------------------------%>
<p>
  <%= form_tag(submissions_path, :method => "get", id: "search-form", class: 'form-inline') do %>
    <%# Add hidden sort and direction to persist these on a search. %>
    <%= hidden_field_tag :direction, params[:direction] %>
    <%= hidden_field_tag :sort, params[:sort] %>

    <div class="form-group">
      <%= text_field_tag :title, params[:title], placeholder: "Search Title", class:'form-control mr-2' %>

      <% if can? :update, Submission %>
        <div class="form-group">
          Completed?
          <%= select_tag(:completed, options_for_select(
            [ ['', -1 ], ['Yes', 1], ['No', 0] ], params[:completed]),
            class:'form-control ml-1 mr-2') %>
        </div>

        <div class="form-group">
          Approved?
          <%= select_tag(:approved, options_for_select(
            [ ['', -1 ], ['Yes', 1], ['No', 0] ], params[:approved]),
            class:'form-control ml-1 mr-2') %>
        </div>

        <div class="form-group">
          Assigned To You?
          <%= check_box_tag(:assigned, 0, params[:assigned], class:'form-control ml-1 mr-2') %>
        </div>
      <% end # if can update %>

      <%= submit_tag "Search", :name => nil, class:'btn btn-primary ml-2 mr-2' %>
      <%= link_to "Clear Search", { :action => "index" }, :method => :get, class:'btn btn-primary mr-4' %>

      <%# This button only toggles the display of the advanced search form. %>
      <button type="button" class="btn btn-primary mr-4" data-toggle="collapse" data-target="#adv_search">Advanced Search</button>
    </div>
  <% end # form_tag %>

  <%= render 'adv_search_form' %>

</p>


<%# --- Display pagination controls ------------------------------------------%>
<div id="submissions">
  <%= render 'pagination' %>
</div>

<%# --- Display submissions --------------------------------------------------%>
<table>
  <tr>
    <%# sortable is defined in application_helper %>
    <th><%= sortable "title" %></th>
    <th><%= sortable "translators.name", "Translator"%></th>
    <th><%= sortable "publication_year", "Year" %></th>
  </tr>

  <% @submissions.each do |submission| %>
    <tr>
      <td>
        <%# Mark entries that not completed and unapproved. %>
        <% if submission.completed and not submission.approved %>
          <span style="color:blue">*</span>
        <% end %>
        <% if not submission.completed %>
          <span style="color:red">*</span>
        <% end %>

        <%= truncate(submission.title, length: 75) %>
      </td>

      <td><%= Translator.find(submission.translator_id).name %></td>
      <td><%= submission.publication_year %></td>

      <td><%= link_to 'Show', submission_path(submission) %>
      <% if can? :update, Submission %>
           : <%= link_to 'Edit', edit_submission_path(submission) %> :
          <%= link_to 'Destroy', submission_path(submission),
             method: :delete,
             data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
  <% end %>

</table>

<p>
  <br/>
  <span style="color:blue">*</span> means the submission is complete but not approved.<br/>
  <span style="color:red">*</span> means the submission is not complete.
</p>

app/views/submissions/new.html.erb
<h1>Create New Submission</h1>

<%= render 'form' %>

app/views/submissions/search.html.erb
<h1>Search Form</h1>
<% disabled ||= false # Form is enabled by default %>


<%= form_tag(submissions_path, :method => "get", id: "search-form") do %>

<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>

<%= submit_tag "Search" %>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>



  <%= render 'error', obj: @submission %>

  <div class="form-group">
    <%= label_tag :title %>
    <%= text_field_tag :title, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= label_tag :work %>
    <%= f.collection_select(:work_id, Work.all, :id, :title, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= label_tag :author %>
    <%= f.collection_select(:author_id, Author.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= label_tag :language %>
    <%= f.collection_select(:language_id, Language.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= label_tag :translator %>
    <%= f.collection_select(:translator_id, Translator.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= label_tag :isbn %>
    <%= text_field_tag :isbn, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= label_tag :oclc %>
    <%= text_field_tag :oclc, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-group">
    <%= label_tag :edition %>
    <%= text_field_tag :edition, class: 'form-control', readonly: disabled %>
  </div>
  <div class="form-check">
    <%= label_tag :is_prose, class:'form-check-label' do %>
      <%= f.check_box :is_prose, class: 'form-check-input', disabled: disabled %>
      Is Prose?
    <% end %>
  </div>
  <div class="form-check">
    <%= label_tag :is_poetry, class:'form-check-label' do %>
      <%= f.check_box :is_poetry, class: 'form-check-input', disabled: disabled %>
      Is Poetry?
    <% end %>
  </div>
  <div class="form-group">
    <%= label_tag :medium %>
    <%= f.collection_select(:medium_id, Medium.all, :id, :name, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
  </div>
  <div class="form-group">
    <%= label_tag :publication_year %>
    <%= text_field_tag :publication_year, class: 'form-control', readonly: disabled %></div>
  <div class="form-group">
    <%= label_tag :notes %>
    <%= f.text_area :notes, class: 'form-control', readonly: disabled %>
  </div>

  <% if can? :update, @submission %>
    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-check">
        <%= label_tag :completed, class:'form-check-label' do %>
          <%= f.check_box :completed, class: 'form-check-input', disabled: disabled %>
          Completed?
        <% end %>
      </div>
    </div>
  <% end %>

  <% if can? :approve, @submission %>
    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-check">
        <%= label_tag :approved, class:'form-check-label' do %>
          <%= f.check_box :approved, class: 'form-check-input', disabled: disabled %>
          Approved?
        <% end %>
      </div>
    </div>

    <div class="form-group d-flex p-2 rounded" style="background-color: lightblue">
      <div class="form-group">
        <%= label_tag "Assign To" %>
        <%= f.collection_select(:entry_id, User.where(role: 'entry'), :id, :email, {:prompt=>true}, {class: 'form-control custom-select', :disabled => disabled}) %>
      </div>
    </div>
  <% end %>

  <%= f.submit style: disabled ? "display:none" : "" %>

<% end %>

app/views/submissions/show.html.erb
<h1><%= @submission.title %></h1>

<%= render 'form', :disabled => true %>